# Generated by Django 3.0.6 on 2021-12-21 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Brand name')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Color name')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Model name')),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_type', models.CharField(db_index=True, max_length=64, verbose_name='Engine type')),
                ('pollutant_class', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A+', max_length=25)),
                ('price', models.CharField(db_index=True, max_length=64, verbose_name='Price')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric'), ('hybrid', 'hybrid')], default='petrol', max_length=25, verbose_name='Fuel type')),
                ('status', models.CharField(blank=True, choices=[('in stock', 'in stock'), ('expected', 'expected'), ('order', 'order'), ('discontinued', 'discontinued')], default='in stock', max_length=25, verbose_name='Status')),
                ('doors', models.CharField(db_index=True, max_length=15, verbose_name='Doors')),
                ('capacity', models.CharField(db_index=True, max_length=15, verbose_name='Capacity')),
                ('gear_case', models.CharField(blank=True, choices=[('mechanical', 'mechanical'), ('automatic', 'automatic')], default='automatic', max_length=25, verbose_name='Gear case')),
                ('number', models.CharField(db_index=True, max_length=15, verbose_name='Number')),
                ('slug', models.SlugField(max_length=40)),
                ('sitting_place', models.CharField(db_index=True, max_length=15, verbose_name='Sitting place')),
                ('first_registration_data', models.DateField()),
                ('engine_power', models.CharField(db_index=True, max_length=15, verbose_name='Engine power')),
                ('color_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.Color')),
                ('dealer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.Model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
