# Generated by Django 3.0.6 on 2021-12-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=15, verbose_name='Category name')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Property name')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(db_index=True, max_length=15, verbose_name='Position')),
                ('metadata', models.CharField(db_index=True, max_length=25, verbose_name='Metadata')),
                ('url', models.CharField(db_index=True, max_length=50, verbose_name='URL')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_picture', to='car.Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('car_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_properties', to='car.Car')),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.Property')),
            ],
        ),
    ]
