# Generated by Django 3.0.6 on 2021-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealerusers',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
    ]
