# Generated by Django 3.0.6 on 2021-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211223_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealerusers',
            name='title',
            field=models.CharField(db_index=True, max_length=64, null=True, verbose_name='Title'),
        ),
    ]
