# Generated by Django 3.1.7 on 2021-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_index=True, max_length=100, verbose_name='City Name')),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(db_index=True, max_length=100, verbose_name='Country Name')),
                ('abbreviation', models.CharField(db_index=True, max_length=20, verbose_name='Short name')),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Dish')),
                ('components', models.CharField(db_index=True, max_length=350, verbose_name='Components')),
                ('recipe', models.TextField()),
            ],
            options={
                'db_table': 'dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Last Name')),
                ('position', models.CharField(db_index=True, max_length=100, verbose_name='Position')),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Menu Name')),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Restaurant Name')),
                ('address', models.CharField(max_length=150, verbose_name='Restaurant Address')),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'season',
                'managed': False,
            },
        ),
    ]
