# Generated by Django 3.0.6 on 2021-12-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.UniqueConstraint(fields=('email',), name='unique email'),
        ),
    ]
