# Generated by Django 3.0.6 on 2021-12-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('formed', 'formed'), ('waiting for payment', 'waiting for payment'), ('paid', 'paid'), ('delivered', 'delivered'), ('completed', 'completed'), ('return', 'return')], default='formed', max_length=25, verbose_name='Status')),
                ('first_name', models.CharField(db_index=True, max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(db_index=True, max_length=64, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(db_index=True, max_length=64, verbose_name='Phone')),
                ('message', models.CharField(db_index=True, max_length=64, verbose_name='Message')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cars.Car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
