# Generated by Django 3.0.6 on 2021-12-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Brand name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine_type', models.CharField(db_index=True, max_length=64, verbose_name='Engine type')),
                ('pollutant_class', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A+', max_length=25)),
                ('price', models.CharField(db_index=True, max_length=64, verbose_name='Price')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('electric', 'electric'), ('hybrid', 'hybrid')], default='petrol', max_length=25, verbose_name='Fuel type')),
                ('status', models.CharField(blank=True, choices=[('in stock', 'in stock'), ('expected', 'expected'), ('order', 'order'), ('discontinued', 'discontinued')], default='in stock', max_length=25, verbose_name='Status')),
                ('doors', models.CharField(db_index=True, max_length=15, verbose_name='Doors')),
                ('capacity', models.CharField(db_index=True, max_length=15, verbose_name='Capacity')),
                ('gear_case', models.CharField(blank=True, choices=[('mechanical', 'mechanical'), ('automatic', 'automatic')], default='automatic', max_length=25, verbose_name='Gear case')),
                ('number', models.CharField(db_index=True, max_length=15, verbose_name='Number')),
                ('slug', models.SlugField(max_length=40)),
                ('sitting_place', models.CharField(db_index=True, max_length=15, verbose_name='Sitting place')),
                ('first_registration_data', models.DateField()),
                ('engine_power', models.CharField(db_index=True, max_length=15, verbose_name='Engine power')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Color name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=15, verbose_name='Category name')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='Property name')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('metadata', models.TextField(blank=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=50, verbose_name='URL')),
                ('upload', models.FileField(upload_to='static/images/cars/%Y/%m/%d/')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_picture', to='cars.Car')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Model name')),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.Brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('car_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_properties', to='cars.Car')),
                ('property_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.Property')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.Color'),
        ),
    ]
