# Generated by Django 3.0.6 on 2022-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211225_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Category name'),
        ),
    ]
