# Generated by Django 3.0.6 on 2022-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220109_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Property name'),
        ),
    ]
