version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'renee-montoya-app-18'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "8083:8080"
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_18
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  app:
    driver: bridge

volumes:
  db_data: