version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'renee-montoya-app-18'
    env_file:
      - .env
    volumes:
      - .:/application
    ports:
      - "8086:8080"
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_20
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql

networks:
  app:
    driver: bridge

volumes:
  db_data: